### PR TITLE
Don't fail when retrieving invalid mappings

### LINKED ISSUE #99: Do not break when invalid mappings in persistence
We get errors on

* https://rdf.wikibase.wiki/wiki/Property:P1
* https://rdf.wikibase.wiki/w/rest.php/wikibase-rdf/v0/mappings

image

This is caused by us adding URL validation, and the wiki still having non-URLs. So should not normally be able to occur. Still, good to make the code a bit more robust against such issues.

Possible fix: Add a forgiving version of https://github.com/ProfessionalWiki/WikibaseRDF/blob/master/src/MappingListSerializer.php#L25-L38 that is used by the code reading from persistence. The existing strict version remains used for deserializing data coming in via the web API. The forgiving version would wrap each object creation in a try catch.

### PR DESCRIPTION
**Pull request by malberts**
Fixes #99 

Simple implementatin of an additional method.

One side-effect, although probably harmless, is once you edit the mappings again it's going to overwrite (i.e. remove) the invalid mapping.

### CODE REVIEW

File: src/MappingListSerializer.php [hunk 1]
```diff
@@ -37,6 +38,23 @@ public function mappingListFromArray( array $mappings ): MappingList {
...
+	 * @param array<int, array{predicate: string, object: string}> $mappings
+	 */
+	public function validMappingListFromArray( array $mappings ): MappingList {
+		$mappingObjects = [];
+		foreach ( $mappings as $mapping ) {
+			try {
+				$mappingObjects[] = new Mapping(
+					predicate: $mapping[self::PREDICATE_KEY],
+					object: $mapping[self::OBJECT_KEY]
+				);
```
Comment (JeroenDeDauw) [inline src/MappingListSerializer.php:51]: Could extract this to mappingFromArray, making the duplication less triggering
